version: 0.2
phases:
  install:
    commands:
      - curl -O https://download.visualstudio.microsoft.com/download/pr/f5c74056-330b-452b-915e-d98fda75024e/18076ca3b89cd362162bbd0cbf9b2ca5/dotnet-sdk-7.0.100-rc.2.22477.23-linux-x64.tar.gz
      - sudo tar -zxvf dotnet-sdk-7.0.100-rc.2.22477.23-linux-x64.tar.gz -C /root/.dotnet
  build:
    commands:
      - dotnet restore aqa.csproj
      - dotnet build aqa.csproj
artifacts:
  files:
    - /var/www/html/Pages/Index.cshtml
